create table if not exists public.votes (
    id bigint generated by default as identity primary key,
    work_id text not null,
    work_title text not null,
    author_key text not null,
    author_name text not null,
    presentation_day numeric null,
    voter_key text not null,
    clarity_score integer not null check (clarity_score between 1 and 5),
    engagement_score integer not null check (engagement_score between 1 and 5),
    relevance_score integer not null check (relevance_score between 1 and 5),
    overall_score integer not null check (overall_score between 1 and 5),
    average_score numeric(6,4) not null,
    submitted_at timestamptz not null default now(),
    constraint votes_unique_voter_work unique (voter_key, work_id)
);

create index if not exists votes_work_idx on public.votes (work_id);
create index if not exists votes_submitted_at_idx on public.votes (submitted_at desc);

alter table public.votes enable row level security;

create policy if not exists "service role full access on votes"
on public.votes
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');